package com.hshim.apisis.api.escape.model

class EscapeThemeSearchCondition(
    val search: String?,
    val onlyOpen: Boolean?,
    val areas: List<String>?,
    val locations: List<String>?,
    val startPlaytime: Int?,
    val endPlaytime: Int?,
    val startPrice: Int?,
    val endPrice: Int?,
    val startDifficulty: Double?,
    val endDifficulty: Double?,
    val startFear: Double?,
    val endFear: Double?,
    val startActivity: Double?,
    val endActivity: Double?,
    val startSatisfy: Double?,
    val endSatisfy: Double?,
    val startProblem: Double?,
    val endProblem: Double?,
    val startStory: Double?,
    val endStory: Double?,
    val startInterior: Double?,
    val endInterior: Double?,
    val startAct: Double?,
    val endAct: Double?,
)