package com.hshim.apisis.api.escape.model

class EscapeThemeOpenAPIResponse(
    val hits: List<Hit>,
) {
    class Hit(
        val title: String,
        val nicknames: List<String>,
        val letters: List<String>?,
        val store_name: String,
        val store_nicknames: List<String>,
        val location: String,
        val area: String,
        val _geo: Geo,
        val address: String,
        val description: String,
        val isopen: Boolean,
        val playtime: Int,
        val poster_loc: String,
        val ref_id: Long,
        val special_tags: List<String>,
        val store_isopen: Boolean,
        val tags: List<String>,
        val price: Int?,
        val thumb_loc: String,
        val activityReviewCount: Double?,
        val difficultyRateTotal: Double?,
        val difficultyReviewCount: Double?,
        val fearRateTotal: Double?,
        val fearReviewCount: Double?,
        val interiorRateTotal: Double?,
        val interiorReviewCount: Double?,
        val isRecommendedTotal: Double?,
        val problemRateTotal: Double?,
        val problemReviewCount: Double?,
        val recommendReviewCount: Double?,
        val reviewCount: Double?,
        val satisfyRateTotal: Double?,
        val satisfyReviewCount: Double?,
        val store_tel: String,
        val store_homepage: String,
        val storyRateTotal: Double?,
        val storyReviewCount: Double?,
        val store_special_tags: String,
        val recommendTotalRating: Double,
        val difficultyTotalRating: Double?,
        val fearTotalRating: Double?,
        val activityTotalRating: Double?,
        val satisfyTotalRating: Double?,
        val problemTotalRating: Double?,
        val storyTotalRating: Double?,
        val interiorTotalRating: Double?,
        val actRateTotal: Double?,
        val actReviewCount: Double?,
        val activityRateTotal: Double?,
        val actTotalRating: Double?,
        val dup_code: Int,
        val isunique: Boolean?,
        val nowtitle: String?,
    ) {
        class Geo(
            val lat: Double,
            val lng: Double,
        )
    }
}